export const courses = () => [
  {
    id: 0,
    name: 'Web Development',
    isFree: true,
    type: 'Beginner',
    ingredients: ['HTML', 'CSS', 'JS'],
    participantNumber: 10,
    durationMonth: 3,
  },
  {
    id: 1,
    name: 'Mobile Development',
    isFree: true,
    type: 'Beginner',
    ingredients: ['Dart', 'Flkutter'],
    participantNumber: 10,
    durationMonth: 3,
  },
  {
    id: 2,
    name: 'UI / UX Design',
    isFree: true,
    type: 'Beginner',
    ingredients: ['Figma', 'Photoshop'],
    participantNumber: 10,
    durationMonth: 3,
  },
  {
    id: 3,
    name: '3D Max',
    isFree: true,
    type: 'Beginner',
    ingredients: ['3D max'],
    participantNumber: 10,
    durationMonth: 3,
  },
  {
    id: 4,
    name: 'Web Development',
    isFree: false,
    type: 'Intermediate',
    ingredients: ['Vue', 'Nuxt'],
    participantNumber: 10,
    durationMonth: 3,
  },
  {
    id: 4,
    name: 'Mobile Development',
    isFree: false,
    type: 'Intermediate',
    ingredients: ['Dart Intermediate', 'Flutter Exclusive'],
    participantNumber: 10,
    durationMonth: 3,
  },
]
